language: python
python:
    - "2.7"
    - "3.6"
    - "3.7-dev"
install:
    - pip install coveralls
    - pip install parameterized
script:
    - "py.test"
    - "coverage run --source=addict setup.py test"
after_success:
    - coveralls
